apiVersion: batch/v1
kind: Job
metadata:
  name: laravel-migration
spec:
  template:
    spec:
      containers:
      - name: migration
        image: laravel-backend:latest
        imagePullPolicy: IfNotPresent
        command: ["php", "artisan", "migrate", "--force"]
        envFrom:
        - configMapRef:
            name: laravel-env
        - secretRef:
            name: laravel-secret
      restartPolicy: OnFailure
